################### English navigation ####################

# main menu
[[main]]
name = "About"
url = "about/"
weight = 1

[[main]]
name = "products"
url = "products/"
weight = 2

  
[[main]]
name = "Contact"
url = "contact/"
weight = 5


# footer menu

[[footer]]
name = "blog"
url = "blog/"






