################### English navigation ####################

# main menu
[[main]]
name = "About"
url = "about/"
weight = 1

[[main]]
name = "course"
url = "course/"
weight = 2

[[main]]
weight = 3
name = "Pages"
hasChildren = true

  [[main]]
  parent = "Pages"
  name = "teacher"
  url = "teacher/"

  [[main]]
  parent = "Pages"
  name = "notice"
  url = "notice/"
 
  
[[main]]
name = "blog"
url = "blog/"
weight = 4
  
[[main]]
name = "Contact"
url = "contact/"
weight = 5


# footer menu

[[footer]]
name = "teacher"
url = "teacher/"




